{{- if .Values.images.pullSecret.create }}
# ServiceAccount for Authorino component (created by Authorino operator)
# Pre-creating it with imagePullSecrets so operator uses this existing SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorino-authorino
  namespace: {{ .Values.namespaces.instances }}
  labels:
    app: authorino
    app.kubernetes.io/name: authorino
    app.kubernetes.io/part-of: rhcl
imagePullSecrets:
- name: {{ .Values.images.pullSecret.name }}
{{- end }}
